import com.yahoofinance.YahooFinance;
import com.yahoofinance.histquotes.HistoricalQuote;
import com.yahoofinance.quotes.stock.Stock;
import com.yahoofinance.quotes.stock.StockQuotes;
import com.yahoofinance.utils.YahooFinanceException;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Timer;
import java.util.TimerTask;

public class App {
    // Define a queue to store stock values and timestamps
    private static final Queue<StockData> stockQueue = new LinkedList<>();

    public static void main(String[] args) {
        Timer timer = new Timer();

        // Schedule a task to run every 5 seconds
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                try {
                    // Fetch the DJIA stock price
                    Stock djia = YahooFinance.get("DJI"); // DJIA ticker symbol
                    double stockPrice = djia.getQuote().getPrice().doubleValue();
                    long timestamp = System.currentTimeMillis();

                    // Store the data in the queue
                    stockQueue.offer(new StockData(stockPrice, timestamp));

                    // Print the stock data for demonstration purposes
                    System.out.println("Stock Price: " + stockPrice + " | Timestamp: " + timestamp);
                } catch (YahooFinanceException e) {
                    e.printStackTrace();
                }
            }
        }, 0, 5000); // Initial delay of 0 ms, repeat every 5000 ms (5 seconds)
    }

    // Inner class to hold stock data
    private static class StockData {
        private final double price;
        private final long timestamp;

        public StockData(double price, long timestamp) {
            this.price = price;
            this.timestamp = timestamp;
        }

        public double getPrice() {
            return price;
        }

        public long getTimestamp() {
            return timestamp;
        }
    }
}


// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package org.example;

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }
